configs:
  v1:
    source: "https://raw.githubusercontent.com/CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml"
    dest: "checkpoints/configs/v1-inference.yaml"
  v2:
    source: "https://raw.githubusercontent.com/Stability-AI/stablediffusion/main/configs/stable-diffusion/v2-inference-v.yaml"
    dest: "checkpoints/configs/v2-inference.yaml"
  xl:
    source: "https://raw.githubusercontent.com/Stability-AI/generative-models/main/configs/inference/sd_xl_base.yaml"
    dest: "checkpoints/configs/xl-base-inference.yaml"

# diffuserbm uses splitted checkpoints because there is no way to convert to ONNX format
checkpoints:
  v1:
    - id: "runwayml/stable-diffusion-v1-5"
      dest: "checkpoints/stable-diffusion-v1.5"
      use_onnx:
        fp32: true
        int8: true
    - id: "lykon/dreamshaper-8"
      dest: "checkpoints/dreamshaper-8"
      use_onnx:
        fp32: true
        int8: true
  v2:
    - id: "stabilityai/stable-diffusion-2-1"
      dest: "checkpoints/stable-diffusion-v2.1"
      use_onnx:
        fp32: true
        int8: true
  xl:
    - id: "stabilityai/sdxl-turbo"
      dest: "checkpoints/sdxl-turbo"
      use_onnx:
        fp32: true
        int8: true
    - id: "lykon/dreamshaper-xl-v2-turbo"
      dest: "checkpoints/dreamshaper-xl-turbo"
      use_onnx:
        fp32: true
        int8: true

upscaler:
  r-esrgan:
    - source: "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth"
      dest: "checkpoints/upscaler/Real-ESRGAN/RealESRGAN_x2plus.pth"
      rate: 2
    - source: "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth"
      dest: "checkpoints/upscaler/Real-ESRGAN/RealESRGAN_x4plus.pth"
      rate: 4
    - source: "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.1/RealESRNet_x4plus.pth"
      dest: "checkpoints/upscaler/Real-ESRGAN/RealESRNet_x4plus.pth"
      rate: 4
    - source: "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pt"
      dest: "checkpoints/upscaler/Real-ESRGAN/RealESRGAN_x4plus_anime_6B.pth"
      rate: 4
    - source: "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-animevideov3.pth"
      dest: "checkpoints/upscaler/Real-ESRGAN/realesr-animevideov3.pth"
      rate: 4
